apiVersion: 1

contactPoints:
  - orgId: 1
    name: 'Platform Admins'
    receivers:
      - uid: email_admin_receiver
        type: email
        settings:
          addresses: '${SMTP_FROM_ADDRESS:-admin@smartcity.com}'
          singleEmail: true

policies:
  - orgId: 1
    receiver: 'Platform Admins'
    group_by: ['alertname', 'severity']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    routes:
      - receiver: 'Platform Admins'
        object_matchers:
          - ['severity', '=', 'critical']
